[package]
name = "fs-share"
version = "0.1.3"
license-file = "LICENSE"
edition.workspace = true
description = "A cross-platform file-sharing CLI application"
keywords = ["file", "share", "tcp", "fs-share", "cli"]
repository = "https://github.com/BiswajitThakur/fs-share.git"
homepage = "https://github.com/BiswajitThakur/fs-share.git"

[dependencies]
share-utils = { version = "0.1.1", path = "../fs-share-utils", package = "fs-share-utils" }

indicatif = "0.17.9"
clap = { version = "4.5.15", features = ["derive"] }

