[package]
name = "fs-share"
version = "0.1.0-dev"
license-file = "LICENSE"
edition.workspace = true
description = "A cross-platform file-sharing CLI application written in Rust. It enables efficient file transfers between devices using TCP and UDP protocols, with real-time progress tracking for each transfer."
repository = "https://github.com/BiswajitThakur/fs-share.git"
homepage = "https://github.com/BiswajitThakur/fs-share.git"

[dependencies]
share-utils = { version = "0.1.0-dev", path = "../fs-share-utils", package = "fs-share-utils" }

clap = { version = "4.5.15", features = ["derive"] }
