[package]
name = "fs-share"
version = "0.1.2"
license-file = "LICENSE"
edition.workspace = true
description = "A cross-platform file-sharing CLI application"
keywords = ["file", "share", "tcu", "udp", "cli"]
repository = "https://github.com/BiswajitThakur/fs-share.git"
homepage = "https://github.com/BiswajitThakur/fs-share.git"

[dependencies]
share-utils = { version = "0.1.1", path = "../fs-share-utils", package = "fs-share-utils" }

clap = { version = "4.5.15", features = ["derive"] }
