[package]
name = "fs-share-utils"
version = "0.1.0"
license-file = "LICENSE"
edition.workspace = true
description = "A utility library for file sharing."
repository = "https://github.com/BiswajitThakur/fs-share.git"
homepage = "https://github.com/BiswajitThakur/fs-share.git"

[dependencies]
dirs = "5.0.1"
indicatif = "0.17.9"
sha2 = "0.10"
